services:
  - type: web
    name: applytrail
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_GOATCOUNTER_SITE
        value: kaungmyat
